# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4ee81322-33fc-4229-9ad3-7f8bd0a19c1e'
  #dockerRegistryServiceConnection: 'dockerhub'
  imageRepository_view: 'viewmicroservice'
  imageRepository_add: 'addmicroservice'
  containerRegistry: 'xxdockerimage.azurecr.io'
  #imageRepository_view: 'view-data'
  #imageRepository_add: 'add-data'
  #containerRegistry: 'docker.io/blackpearl001'
  dockerfilePath_view: 'Dockerfile_view_data'
  dockerfilePath_add: 'Dockerfile_add_data'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'xxdockerimage6490c5db-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: dev
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)  # Use the name of your Azure Service Connection
        command: 'login'
    #- task: Docker@2
    #  displayName: Build and push an image view_microservice
    #  inputs:
    #    command: build
    #    repository: $(imageRepository_view)
    #    dockerfile: $(dockerfilePath_view)
    #    containerRegistry: $(dockerRegistryServiceConnection)
    #    buildContext: .
    #    tags: |
    #      $(tag)
    #    addPipelineData: true
    - task: Bash@3
      displayName: 'Create custom buildx builder'
      inputs:
        targetType: 'inline'
        script: |
          docker buildx create --name mybuilder
          docker buildx ls
          docker buildx use mybuilder
          docker buildx inspect --bootstrap

    - task: Bash@3
      displayName: 'Build and Push view_microservice Docker Image using Buildx'
      inputs:
        targetType: 'inline'    
        script: |
          docker buildx build -f $(dockerfilePath_view) --platform linux/amd64,linux/arm64 -t $(containerRegistry)/$(imageRepository_view):$(tag) --push .


    #- task: Docker@2
    #  displayName: Build and push an image add_microservice
    #  inputs:
    #    command: build
    #    repository: $(imageRepository_add)
    #    dockerfile: $(dockerfilePath_add)
    #    containerRegistry: $(dockerRegistryServiceConnection)
    #    buildContext: .
    #    tags: |
    #      $(tag)
    #    addPipelineData: true

    - task: Bash@3
      displayName: 'Build and Push add_microservice Docker Image using Buildx'
      inputs:
        targetType: 'inline'  
        script: |
          docker buildx build -f $(dockerfilePath_add) --platform linux/amd64,linux/arm64 -t $(containerRegistry)/$(imageRepository_add):$(tag) --push .

    - upload: manifests
      artifact: manifests

    #- task: Bash@3
    #  displayName: Cleanup docker image 
    #  inputs:
    #    targetType: 'inline'
    #    script: |
    #      docker rmi $(containerRegistry)/$(imageRepository_view):$(tag)
    #      docker rmi $(containerRegistry)/$(imageRepository_add):$(tag)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: dev
      vmImage: $(vmImageName)
    environment: 'rahulwaynepyappk8sistio.pyapp-istio-test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository_view):$(tag)
                $(containerRegistry)/$(imageRepository_add):$(tag)