---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: view-service
spec:
  selector:
    app: view-microservice
  ports:
    - protocol: TCP
      port: 5002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: add-microservice
  ports:
    - protocol: TCP
      port: 5001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  selector:
    app: index-microservice
  ports:
    - protocol: TCP
      port: 5000
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: pyapp-gateway
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pyapp-virtualservice
spec:
  hosts:
  - "*"  # Match all hosts
  gateways:
  - pyapp-gateway  # Assuming 'pyapp-gateway' is your Istio Gateway
  http:
  - match:
    - uri:
        prefix: /data
    route:
    - destination:
        host: add-service.pyapp-istio-test.svc.cluster.local
        port:
          number: 5001
  - match:
    - uri:
        prefix: /view
    route:
    - destination:
        host: view-service.pyapp-istio-test.svc.cluster.local
        port:
          number: 5002
  - match:
    - uri:
        prefix: /delete
    route:
    - destination:
        host: view-service.pyapp-istio-test.svc.cluster.local
        port:
          number: 5002
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: index-service.pyapp-istio-test.svc.cluster.local
        port:
          number: 5000